# Generated by Django 2.0.7 on 2018-08-24 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='邮箱'),
        ),
        migrations.AddField(
            model_name='message',
            name='name',
            field=models.CharField(default='', max_length=10, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='message',
            name='messages',
            field=models.CharField(max_length=500, verbose_name='留言信息'),
        ),
        migrations.AlterField(
            model_name='message',
            name='phone_num',
            field=models.CharField(max_length=11, verbose_name='联系地址'),
        ),
    ]
